### ISSUE TITLE
Missing Compiler options such as ADA , C#

### ISSUE THREAD

**Issue by Eldadc** [madduci/docker-compiler-explorer#5]
Hi,

Missing Compiler options such ADA , C# ....
I have just c++ , c , pyhon 
Any Suggestions ?

Thanks

**Comment by madduci** [comment]
Hi
For the other compiler options, please refer to the Compiler Explorer
repository, in the specific look for the configuration files for ADA, C# or
other languages that you need.

All you have to do is then clone this repository, add the specific file
configuration and add it in the Dockerfile. Hope it helps!

Il mar 7 dic 2021, 08:30 N C ***@***.***> ha scritto:

**Comment by Eldadc** [comment]
Hi,

So Your docker is set just for python,c,c++ ?
I am working in offline network environment without internet.
I just downloaded the image from Docker hub and run with simple docker command line.

Thanks

**Comment by madduci** [comment]
Exactly. Mine is just for C++.

But you can build it with your own tools and then import the final image in
your offline environment.

Il mar 7 dic 2021, 10:02 N C ***@***.***> ha scritto:

**Comment by Eldadc** [comment]
I am working in offline network so I can not build a new image.
Can you instruct me how to add lang ?

Thanks

**Comment by madduci** [comment]
Thank you for your patient, I've just found out that the issue was still open in the project.

You have to refer to the official Compiler Explorer Repository for configuring additional languages in Compiler Explorer.

In an offline Network I don't think this will work, but if you need ADA or C# compilers in Debian, you'll need to install those deb packages in this image during the RUN step.
